version: "3.10"

services:
  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: fabienzucchet
      DOCKER_INFLUXDB_INIT_BUCKET: go-monitoring-tool
    volumes:
      - $PWD/.docker/influxdb/data:/var/lib/influxdb2
      - $PWD/.docker/influxdb/config:/etc/influxdb2

  mongodb:
    image: mongo:5.0-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - $PWD/.docker/mongodb/data:/data/db
      - $PWD/.docker/mongodb/mongod.conf:/etc/mongod.conf
